-- ══════════════════════════════════════════════════════════════════════════════
-- CADASTRO MESTRE DE FORNECEDORES — DE-PARA UNIFICADO
-- Migration: migration_fornecedores_depara.sql
-- Data: 2026-03-18
--
-- Tabela cq_fornecedores: cadastro unificado com código ATAK, nome oficial,
-- apelido e aliases (nomes variantes usados em planilhas).
-- ══════════════════════════════════════════════════════════════════════════════

BEGIN;

-- ════════════════════════════════════════════════════════════════════════════
-- 1. TABELA PRINCIPAL
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS cq_fornecedores (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo_atak     TEXT NOT NULL UNIQUE,
  nome_oficial    TEXT NOT NULL,
  apelido         TEXT NOT NULL,
  aliases         TEXT[] NOT NULL DEFAULT '{}',
  ativo           BOOLEAN NOT NULL DEFAULT true,
  criado_em       TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cq_fornecedores_codigo ON cq_fornecedores(codigo_atak);
CREATE INDEX IF NOT EXISTS idx_cq_fornecedores_apelido ON cq_fornecedores(apelido);
CREATE INDEX IF NOT EXISTS idx_cq_fornecedores_aliases ON cq_fornecedores USING GIN(aliases);

COMMENT ON TABLE cq_fornecedores IS 'Cadastro mestre unificado de fornecedores (frigoríficos). DE-PARA planilha → ATAK.';
COMMENT ON COLUMN cq_fornecedores.codigo_atak IS 'Código do fornecedor no sistema ATAK (ex: 60084)';
COMMENT ON COLUMN cq_fornecedores.nome_oficial IS 'Razão social ou nome oficial no ATAK';
COMMENT ON COLUMN cq_fornecedores.apelido IS 'Nome curto usado no dia-a-dia (ex: GOLD CARNES)';
COMMENT ON COLUMN cq_fornecedores.aliases IS 'Array com todos os nomes variantes encontrados em planilhas';

-- ════════════════════════════════════════════════════════════════════════════
-- 2. RLS
-- ════════════════════════════════════════════════════════════════════════════

ALTER TABLE cq_fornecedores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS cq_fornecedores_select ON cq_fornecedores;
CREATE POLICY cq_fornecedores_select ON cq_fornecedores
  FOR SELECT USING (true);

DROP POLICY IF EXISTS cq_fornecedores_insert ON cq_fornecedores;
CREATE POLICY cq_fornecedores_insert ON cq_fornecedores
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM cq_perfis_usuario WHERE user_id = auth.uid() AND perfil IN ('administrador'))
  );

DROP POLICY IF EXISTS cq_fornecedores_update ON cq_fornecedores;
CREATE POLICY cq_fornecedores_update ON cq_fornecedores
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM cq_perfis_usuario WHERE user_id = auth.uid() AND perfil IN ('administrador'))
  );

-- ════════════════════════════════════════════════════════════════════════════
-- 3. FUNÇÃO: NORMALIZAR FORNECEDOR
-- Recebe um nome qualquer e retorna o fornecedor normalizado
-- ════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION cq_normalizar_fornecedor(p_nome TEXT)
RETURNS TABLE (
  codigo_atak TEXT,
  nome_oficial TEXT,
  apelido TEXT,
  encontrado BOOLEAN
)
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_nome TEXT;
  v_rec RECORD;
BEGIN
  IF p_nome IS NULL OR trim(p_nome) = '' THEN
    RETURN QUERY SELECT NULL::TEXT, NULL::TEXT, NULL::TEXT, false;
    RETURN;
  END IF;

  v_nome := upper(trim(regexp_replace(p_nome, '\s+', ' ', 'g')));

  -- 1. Busca exata por apelido
  SELECT f.codigo_atak, f.nome_oficial, f.apelido INTO v_rec
  FROM cq_fornecedores f
  WHERE upper(f.apelido) = v_nome AND f.ativo = true
  LIMIT 1;

  IF FOUND THEN
    RETURN QUERY SELECT v_rec.codigo_atak, v_rec.nome_oficial, v_rec.apelido, true;
    RETURN;
  END IF;

  -- 2. Busca por alias
  SELECT f.codigo_atak, f.nome_oficial, f.apelido INTO v_rec
  FROM cq_fornecedores f
  WHERE v_nome = ANY(f.aliases) AND f.ativo = true
  LIMIT 1;

  IF FOUND THEN
    RETURN QUERY SELECT v_rec.codigo_atak, v_rec.nome_oficial, v_rec.apelido, true;
    RETURN;
  END IF;

  -- 3. Busca por código
  SELECT f.codigo_atak, f.nome_oficial, f.apelido INTO v_rec
  FROM cq_fornecedores f
  WHERE f.codigo_atak = v_nome AND f.ativo = true
  LIMIT 1;

  IF FOUND THEN
    RETURN QUERY SELECT v_rec.codigo_atak, v_rec.nome_oficial, v_rec.apelido, true;
    RETURN;
  END IF;

  -- 4. Busca parcial no nome oficial
  SELECT f.codigo_atak, f.nome_oficial, f.apelido INTO v_rec
  FROM cq_fornecedores f
  WHERE upper(f.nome_oficial) LIKE '%' || v_nome || '%' AND f.ativo = true
  LIMIT 1;

  IF FOUND THEN
    RETURN QUERY SELECT v_rec.codigo_atak, v_rec.nome_oficial, v_rec.apelido, true;
    RETURN;
  END IF;

  -- Não encontrado
  RETURN QUERY SELECT NULL::TEXT, NULL::TEXT, p_nome, false;
END;
$$;

-- ════════════════════════════════════════════════════════════════════════════
-- 4. SEED: INSERIR TODOS OS FORNECEDORES
-- ════════════════════════════════════════════════════════════════════════════

INSERT INTO cq_fornecedores (codigo_atak, nome_oficial, apelido, aliases) VALUES
('60239', 'COUROS 3G - FAXINAL', 'COUROS FAXINAL', ARRAY['3G']),
('81096', 'ABATEDOURO DE BOVINOS LAGOA GRANDE LTDA', 'ABLG - ARAUCARIA - PR', ARRAY['ABLG']),
('50052', 'DISTRIB CARNES DERIVADOS ALEXANDRE LTDA', 'DISTRIB CARNES DERIVADOS ALEXANDRE LTDA', ARRAY['ALEXANDRE']),
('60285', 'FRIGORIFICO ALIANÇA EIRELI', 'ALIANÇA', ARRAY['ALIANCA','ALIANÇA']),
('60013', 'ANGUS CARNES LTDA', 'ANGUS CARNES - WESTFALIA - RS', ARRAY['ANGUS']),
('60052', 'MATADOURO MUNICIPAL DE ARABUTÃ', 'ARABUTA', ARRAY['ARABUTA']),
('60092', 'ASSOCIACAO DOS ACOUGUEIROS DE CIANORTE - ASAC', 'ASAC - CIANORTE', ARRAY['ASSOCIAÇÃO','ASSOCIAÇÃO CIANORTE','ASAC']),
('60009', 'FRIGOBECKER LTDA', 'FRIGOBECKER', ARRAY['BECKER','FRIGOBECKER']),
('60352', 'BERRANTE ALIMENTOS LTDA', 'BERRANTE ALIMENTOS LTDA', ARRAY['BERRANTE']),
('60318', 'FRIGORIFICO BOI DOURADO', 'BOI DOURADO', ARRAY['BO DOURADO','BOI DOURADO']),
('60027', 'JOSÉ FERMINO MAGALHÃES ME', 'JOSÉ FERMINO MAGALHÃES ME', ARRAY['BOI GORDO']),
('60342', 'BOI NOBRE ALIMENTOS LTDA', 'BOI NOBRE ALIMENTOS LTDA', ARRAY['BOI NOBRE','NOBRE']),
('60262', 'FRIGORIFICO BOI SUL LTDA', 'BOI SUL', ARRAY['BOI SUL']),
('60054', 'COOPERATIVA AGROPECUARIA BONSUCESSO', 'COOPERATIVA AGROPECUARIA BONSUCESSO', ARRAY['BOM SUCESSO']),
('60113', 'BOSSONI E BOSSONI LTDA', 'BOSSONI - LUPERCIO', ARRAY['BOSSONI']),
('60133', 'CALIBRE DISTRIBUIDORA DE CARNES LTDA', 'CALIBRE DISTRIBUIDORA - FLORAI', ARRAY['CALIBRE']),
('60163', 'FRIGORIFICO CAMPO DO GADO AGROINDUSTRIA LTDA', 'FRIGORIFICO CAMPO DO GADO', ARRAY['CAMPO DO GADO']),
('60108', 'ABATEDOURO CAPRINI LTDA', 'CAPRINI', ARRAY['CAPRINI']),
('60308', 'FRIGORIFICO CARNE NOBRE LTDA', 'CARNE NOBRE', ARRAY['CARNE NOBRE']),
('60017', 'MARCIO LOPES CAVALCANTE', 'CAVALCANTE', ARRAY['CAVALCANTE','MARCIO CALVACANTE','MARCIO CAVALCANTE']),
('60111', 'FRIGOCENTER FRIGORIFICO LTDA', 'FRIGOCENTER', ARRAY['CENTER']),
('50047', 'FRIGORIFICO CHAPARRAL LTDA', 'FRIGORIFICO CHAPARRAL LTDA', ARRAY['CHAPARRAL']),
('60012', 'FRIGOLIDER LTDA', 'FRIGOLIDER - COLIDER - MT', ARRAY['COLIDER']),
('60043', 'FRIGONESI FRIGORIFICO LTDA', 'FRIGONESI', ARRAY['COMINESI','NESI']),
('60187', 'FRIGOMATA LTDA - ME', 'FRIGOMATA', ARRAY['DA MATA']),
('60004', 'FRIGODASKO LTDA', 'FRIGODASKO', ARRAY['DASKO']),
('60310', 'FRIGODIA FRIGORIFICA DIA LTDA', 'FRIGODIA', ARRAY['DIA','FRIGODIA']),
('50061', 'DICAVEL DISTRIBUIDORA DE CARNES LTDA', 'DICAVEL', ARRAY['DISTRIBUIDORA','DICAVEL']),
('60270', 'FRIGORIFICO D'' MATTA COMERCIO E INDUSTRIA LTDA', 'D'' MATTA', ARRAY['D''MATTA','D MATTA']),
('60341', 'BOI BARÃO ABATEDOURO LTDA', 'BOI BARÃO', ARRAY['EJ']),
('60077', 'ENTREPOSTO SAO JOSE LTDA', 'CAJOBI', ARRAY['ENTREPOSTO','ENTREPOSTO SÃO JOSÉ','SÃO JOSE','SAO JOSE','SÃO JOSÉ','SAO JOSÉ','SÃO JOSÉ CAJOBI']),
('60124', 'FRIGORIFICO EP LTDA', 'FRIGORIFICO EP', ARRAY['EP']),
('60276', 'MATADOURO ESPERANÇA LTDA', 'ESPERANCA', ARRAY['ESPERANCA','ESPERANÇA']),
('60337', 'CINCO ESTRELAS ARTIGOS DE COURO LTDA', 'CINCO ESTRELAS', ARRAY['ESTRELA']),
('60351', 'FRIGORIFICO ESTRELA DO SUL LTDA', 'ESTRELA DO SUL', ARRAY['ESTRELA DO SUL']),
('60028', 'FRIGOEURO LTDA', 'FRIGOEURO', ARRAY['EURO']),
('60350', 'FRIGORIFICO REGIONAL PIEMONTE DA CHAPADA', 'FRIGOCESAR', ARRAY['FIROGO CESAR','FRIGOCESAR']),
('60372', 'FRASSUL COMERCIO DE ALIMENTOS LTDA', 'FRASSUL', ARRAY['FRASSUL']),
('60114', 'FRIBAL FRIGORIFICO BALANCIN LTDA', 'FRIBAL - BALANCIN', ARRAY['FRIBAL']),
('60053', 'FRIBAZ FRIGORIFICO LTDA', 'FRIBAZ', ARRAY['FRIBAZ']),
('60381', 'FRIGONOR FRIGORIFICO & COMERCIO LTDA', 'FRIGONOR', ARRAY['FRIGONOR']),
('60093', 'FRIGORAES AGROINDUSTRIA LTDA', 'FRIGORAES', ARRAY['FRIGORAES','FRIGORAIS','RAES']),
('60224', 'FRIGORINI FRIGORIFICA LTDA', 'FRIGORINI', ARRAY['FRIGORINI']),
('60003', 'FRIGOTERRA FRIGORIFICO LTDA', 'FRIGOTERRA', ARRAY['FRIGOTERRA','TERRA']),
('60235', 'FRIGOVEMA FRIGORIFICO LTDA', 'IVINHEMA', ARRAY['FRIGOVEMA','VEMA']),
('60137', 'FRIJACUIPE MATADOURO E FRIGORIFICO LTDA', 'FRIJACUIPE', ARRAY['FRIJACUIPE']),
('50090', 'FRIGORIFICO FRILEM LTDA', 'FRILEM', ARRAY['FRILEM']),
('60370', 'FRIMATOS AGROINDUSTRIA LTDA', 'FRIMATOS', ARRAY['FRIMATOS','MATOS']),
('60063', 'FRINORA FRIGORIFICO DO NORTE LTDA', 'FRINORA/FRIOURO', ARRAY['FRINORA']),
('60353', 'FRISPAR FRIGORIFICO SUDOESTE DO PARANA LTDA', 'FRISPAR', ARRAY['FRISPAR']),
('60331', 'FRIZONTE - INDUSTRIA DE ALIMENTOS LTDA', 'FRIZONTE', ARRAY['FRIZONTE']),
('60084', 'GOLD CARNES LTDA', 'GOLD CARNES', ARRAY['GOLD','GOLD CARNES']),
('60140', 'J GUSMAO & CIA LTDA', 'J GUSMAO', ARRAY['GUSMÃO','GUSMAO','J GUSMAO']),
('60361', 'FRIGO HIPER CARNE LTDA', 'FRIGO HIPER CARNE', ARRAY['HIPER']),
('60362', 'FRIGORIFICO INTER ABATE E COMERCIO DE CARNES', 'FRIGO INTER ABATE', ARRAY['INTER']),
('60179', 'FRIGORIFICO IPER LTDA', 'FRIGORIFICO IPER', ARRAY['IPER']),
('50050', 'ITAJARA COMERCIO DE CARNES LTDA', 'ITAJARA', ARRAY['ITAJARA']),
('60334', 'JACOB & BATTISTI LTDA', 'JACOB & BATTISTI', ARRAY['JACOB']),
('60344', 'FRIGOMAIS LTDA', 'FRIGOMAIS', ARRAY['JAGUAR','JARAGUA']),
('96041', 'JEAN JORGE STECKER', 'JEAN', ARRAY['JEAN']),
('60148', 'JEAN CARLOS DOS SANTOS - CARNES - ME', 'JEAN CARLOS DOS SANTOS', ARRAY['JEAN CARLOS','ME']),
('60260', 'J P S DISTRIBUIDORA DE CARNES LTDA', 'J P S / GRAND BULL', ARRAY['JPS']),
('50058', 'J.R. LEME', 'J.R. LEME', ARRAY['JR']),
('50033', 'J S FERREIRA FRIGORIFICO LTDA', 'J S FERREIRA', ARRAY['JS']),
('50092', 'FRIGORIFICO KLEIN LTDA', 'FRIGORIFICO KLEIN', ARRAY['KLEIN']),
('60273', 'KM DISTRIBUIDORA DE CARNES LTDA', 'KM DISTRIBUIDORA', ARRAY['KM']),
('60112', 'FRIGORIFICO LEME LTDA', 'JOSÉ RONALDO', ARRAY['LEME']),
('60168', 'DISCA LUZ DISTRIBUIDORA DE CARNES EIRELI', 'DISCA LUZ', ARRAY['LUZ']),
('60097', 'FRIGORIFICO LUZENCE LTDA', 'FRIGORIFICO LUZENCE', ARRAY['LUZENSE']),
('60055', 'FRIGOESTE LTDA', 'MAGIA - FRIOESTE', ARRAY['MAGIA']),
('60010', 'FRIGORIFICO MAGISTRAL LTDA', 'ORION & MAGISTRAL', ARRAY['MAGISTRAL','ORION']),
('60049', 'MARCELO DOS SANTOS ME', 'FRIGONI/FRIGODINO', ARRAY['MARCELO SANTOS']),
('60120', 'MARCIO LOPES CAVALCANTE', 'MARCIO LOPES CAVALCANTE', ARRAY['MARCIO']),
('60309', 'FRIGORIFICO MAX LTDA', 'MAX', ARRAY['MAX']),
('60144', 'MBS FRIGORIFICO LTDA', 'MBS FRIGORIFICO', ARRAY['MBS']),
('50068', 'FRIGORIFICO FRIGOMENDES LTDA', 'FRIGOMENDES', ARRAY['MENDES']),
('60121', 'MG COUROS LTDA', 'MG COUROS', ARRAY['MG','MG COUROS']),
('60175', 'FRIGORIFICO MODELO LTDA', 'FRIGORIFICO MODELO', ARRAY['MODELO']),
('60078', 'MONTALFRIG LTDA', 'MONTALFRIG', ARRAY['MONTALFRIG']),
('60272', 'FRIGORIFICO MORRO AGUDO', 'MORRO AGUDO', ARRAY['MORRO AGUDO']),
('60106', 'FRIGORIFICO MOYA LTDA', 'COLORADO', ARRAY['MOYA']),
('60136', 'FRIGORIFICO MUQUEM DO SAO FRANCISCO LTDA', 'MUQUEM', ARRAY['MUQUEM']),
('60116', 'FRIGORIFICO NOSSA SENHORA APARECIDA LTDA', 'NOSSA SENHORA APARECIDA', ARRAY['NOSSA SENHORA']),
('60149', 'FRIGORIFICO NOVA ALIANCA LTDA', 'NOVA ALIANCA', ARRAY['NOVA ALIANÇA','NOVA ALIANCA']),
('60037', 'NOVA PRATA FRIGORIFICO LTDA', 'NOVA PRATA', ARRAY['NOVA PRATA']),
('60332', 'MATADOURO O T J LTDA EPP', 'MATADOURO O T J LTDA EPP', ARRAY['OTJ']),
('60025', 'FRIGORIFICO OURO VERDE LTDA', 'OURO VERDE', ARRAY['OURO VERDE']),
('60304', 'FRIGORIFICO PAI NOSSO LTDA', 'PAI NOSSO', ARRAY['PAI NIOSSO','PAI NOSSO']),
('60320', 'FRIGORIFICO PARACATU', 'PARACATU', ARRAY['PARACATU']),
('60377', 'PRO BOI CARNES LTDA', 'PRO BOI CARNES', ARRAY['PRO BOI','PROBOI']),
('60240', 'DISTRIBUIDORA DE CARNES RANK LTDA', 'RANK', ARRAY['RANK']),
('60371', 'REAL SUBPRODUTOS LTDA', 'REAL SUBPRODUTOS', ARRAY['REAL']),
('50046', 'RECRISUL LTDA', 'RECRISUL', ARRAY['RECRISUL']),
('60138', 'FRIGORIFICO REGIONAL DE ALAGOINHAS LTDA', 'REGIONAL DE ALAGOINHAS', ARRAY['REGIONAL']),
('60180', 'ABATE E DISTRIBUICAO DE CARNES RODEIO LTDA', 'RODEIO', ARRAY['RODEIO']),
('60178', 'FRIG ROSO & DALL AGNOL LTDA', 'ROSO & DALL AGNOL', ARRAY['ROSO']),
('60199', 'ROSSATO COMERCIO DE CARNES LTDA', 'ROSSATO', ARRAY['ROSSATO']),
('60135', 'ROSSI FRIGORIFICO LTDA', 'ROSSI FRIGORIFICO', ARRAY['ROSSI']),
('60058', 'FRIGORIFICO SALTO VELOSO LTDA', 'SALTO VELOSO', ARRAY['SALTO VELOSO','VELOSO']),
('60045', 'FRIGORIFICO SCAPINI LTDA', 'SCAPINI', ARRAY['SCAPINI']),
('60006', 'FRIGOSCHAEDLER LTDA', 'FRIGOSCHAEDLER', ARRAY['SCHAEDLER']),
('60349', 'FRIGOSSERRA LTDA', 'FRIGOSSERRA', ARRAY['SERRA']),
('60348', 'FRIGORIFICO SERRANO LTDA', 'FRIGORIFICO SERRANO', ARRAY['SERRANO']),
('60356', 'COMERCIO DE CARNES SIVIERO LTDA', 'SIVIERO', ARRAY['SIVIERO']),
('60110', 'SOMA DISTRIBUIDORA DE CARNES LTDA', 'SOMA - CANAA', ARRAY['SOMA']),
('60095', 'FRIGORIFICO SAO FRANCISCO LTDA', 'SAO FRANCISCO', ARRAY['SÃO FRANCISCO','SAO FRANCISCO']),
('60169', 'MATADOURO SAO GERALDO LTDA', 'SAO GERALDO', ARRAY['SÃO GERALDO','SAO GERALDO']),
('60297', 'TALISMA CARNES LTDA', 'TALISMA', ARRAY['TALISMA']),
('60155', 'FRIGORIFICO TMJ LTDA', 'FRIGORIFICO TMJ', ARRAY['TMJ']),
('60062', 'FRIGOTOTI LTDA', 'FRIGOTOTI', ARRAY['TOTI']),
('60382', 'UNIFRIGO FRIGORIFICO LTDA', 'UNIFRIGO', ARRAY['UNIFRIG']),
('60141', 'VADECAR MATADOURO LTDA', 'VADECAR', ARRAY['VADECAR']),
('60322', 'BORRAZOPOLIS DISTRIBUIDORA', 'BORRAZOPOLIS', ARRAY['VALDEIR']),
('60072', 'FRIGORIFICO VALE DO PRATA LTDA', 'VALE DO PRATA', ARRAY['VALE DA PRATA','VALE DO PRATA']),
('60125', 'VALE DO BOI ALIMENTOS LTDA', 'VALE DO BOI', ARRAY['VALE DO BOI']),
('60094', 'FRIGOVEREDA LTDA', 'VEREDA', ARRAY['VEREDA']),
('60281', 'FRIGORIFICO VIANNA LTDA', 'VIANNA', ARRAY['VIANNA']),
('50025', 'VIDAURRE INDUSTRIA E COMERCIO LTDA', 'FRIGORIFICO VIDAURRE', ARRAY['VIDAURRE']),
('60096', 'FRIGOVIEIRA LTDA', 'RIO DA PRATA', ARRAY['VIEIRA']),
('60046', 'PAULO VIOLA FRIGORIFICO LTDA', 'PAULO VIOLA', ARRAY['VIOLA']),
('60339', 'NILSON FERNANDO WOLPI DE OLIVEIRA LTDA', 'WOLPI', ARRAY['WOLPI']),
('50051', 'ABATEDOURO WS LTDA ME', 'ABATEDOURO WS', ARRAY['WS'])
ON CONFLICT (codigo_atak) DO UPDATE SET
  nome_oficial = EXCLUDED.nome_oficial,
  apelido = EXCLUDED.apelido,
  aliases = EXCLUDED.aliases,
  atualizado_em = now();

-- ════════════════════════════════════════════════════════════════════════════
-- 5. FUNÇÃO: LISTAR FORNECEDORES (para autocomplete)
-- ════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION cq_listar_fornecedores(p_termo TEXT DEFAULT NULL)
RETURNS TABLE (
  codigo_atak TEXT,
  nome_oficial TEXT,
  apelido TEXT,
  aliases TEXT[]
)
LANGUAGE sql SECURITY DEFINER STABLE AS $$
  SELECT f.codigo_atak, f.nome_oficial, f.apelido, f.aliases
  FROM cq_fornecedores f
  WHERE f.ativo = true
    AND (
      p_termo IS NULL
      OR upper(f.apelido) LIKE '%' || upper(trim(p_termo)) || '%'
      OR upper(f.nome_oficial) LIKE '%' || upper(trim(p_termo)) || '%'
      OR f.codigo_atak LIKE '%' || trim(p_termo) || '%'
      OR upper(trim(p_termo)) = ANY(f.aliases)
    )
  ORDER BY f.apelido;
$$;

COMMIT;
