-- ════════════════════════════════════════════════════════════════════════════
-- ORDEM OFICIAL DE REBUILD — Banco RH/SST (Classic Couros)
-- Última homologação: 2026-04-13 (0 erros, PostgreSQL 16)
-- ════════════════════════════════════════════════════════════════════════════
--
-- EXECUÇÃO:
--   psql -d <banco> -f 00_PREAMBULO.sql
--   psql -d <banco> -f FUNDACAO_BANCO_v2.sql
--   ... (na ordem abaixo)
--
-- PRÉ-REQUISITOS:
--   - PostgreSQL 16+
--   - Em ambiente Supabase: nenhum pré-requisito adicional
--   - Em ambiente local: 00_PREAMBULO.sql cria stubs necessários
--
-- ════════════════════════════════════════════════════════════════════════════
--
--  #  ARQUIVO                              OBJETOS        DOMÍNIO
-- ──  ─────────────────────────────────────  ─────────────  ────────────────
--  1  00_PREAMBULO.sql                      extensions,    Ambiente
--                                           stubs auth,
--                                           roles
--
--  2  FUNDACAO_BANCO_v2.sql                 13 tabelas,    RH Core
--                                           triggers,      (estrutura
--                                           functions      organizacional)
--
--  3  00_schema_supabase.sql                10 tabelas,    RH Core
--                                           views,         (colaboradores,
--                                           RPC            ponto, custos)
--
--  4  schema_rh_sst_completo.sql            16 tabelas,    RH + SST
--                                           indexes,       (funcionarios,
--                                           RLS            ASO, EPIs)
--
--  5  MODULO_SST_v2.sql                     10 tabelas,    SST
--                                           trigger        (acidentes, OS,
--                                                          treinamentos)
--
--  6  schema_recrutamento_selecao.sql       6 tabelas      Recrutamento
--
--  7  schema_lideranca.sql                  4 tabelas,     Liderança
--                                           function
--
--  8  SEGURANCA_SUPABASE.sql                7 tabelas,     Segurança
--                                           12 functions,  (RLS, RBAC,
--                                           RLS+policies   perfis)
--     ↑ ANTES de DESLIGAMENTOS e SAUDE_MENTAL (dependência: has_perfil)
--
--  9  MODULO_DESLIGAMENTOS_TURNOVER.sql     4 tabelas,     Desligamentos
--                                           3 RPCs,        Turnover
--                                           5 views
--
-- 10  MODULO_SAUDE_MENTAL.sql               4 tabelas,     Saúde Mental
--                                           6 RPCs,
--                                           3 views
--
-- 11  TABELAS_RH_CORE.sql                   17 tabelas     Processos,
--                                                          Ponto, Férias,
--                                                          Documentos
--
-- 12  TABELAS_SST.sql                       18 tabelas     Estoque EPI,
--                                                          Faturas, CIPA,
--                                                          eSocial
--
-- 13  TABELAS_GESTOR.sql                    24 tabelas     Motor Score,
--                                                          Agentes IA,
--                                                          Orquestração
--
-- 14  TABELAS_FINANCEIRO.sql                16 tabelas     Custos, CTE,
--                                                          Folha Pgto
--
-- 15  TABELAS_ETL.sql                       39 tabelas     Staging,
--                                                          Integração,
--                                                          Produção
--
-- 16  RLS_TABELAS_NOVAS.sql                 11 tabelas     Segurança
--                                           22 policies    (patch RLS)
--
-- 17  VIEWS_APLICACAO.sql                   16 views       Dashboard RPCs
--                                                          (motor, absenteísmo)
--
-- 18  FUNCOES_APLICACAO.sql                 18 RPCs        Frontend
--                                                          (dashboards,
--                                                          CRUD, ETL)
--
-- 19  VIEWS_FRONTEND_COMPATIBILIDADE.sql    2 views        Compatibilidade
--                                                          (vw_funcionario_base,
--                                                          rh_colaboradores)
--
-- 20  MODULO_DECISAO_EXPERIENCIA.sql        1 tabela,      Decisão executiva
--                                           2 RPCs,        sobre contratos
--                                           1 view,        de experiência
--                                           4 RLS policies (45d e 90d)
--
-- 21  MODULO_CIPA_ACOES.sql                 1 tabela,      Ações/deliberações
--                                           3 RLS policies de reuniões CIPA
--                                                          (backend da aba
--                                                          "Ações" em cipa.html)
--
-- 22  UNIFICACAO_SST.sql                    1 tabela       Sprint 1 P0: família
--                                           (sst_aso_config) sst_* vira canônica
--                                           ALTERs em      (ASOs, treinamentos,
--                                           sst_acidente/  acidentes); migra
--                                           sst_aso/       dados das rh_* legadas
--                                           sst_tipo_trein e revoga escrita nelas
--                                           4 RLS policies (PLANO_CORRECOES_SIGA)
--
-- 23  CORRECOES_CIPA.sql                    2 colunas      Sprint 1 P0: CIPA
--                                           (deliberacoes, (deliberações em coluna
--                                           empresa_slug)  própria; empresa no
--                                                          canal de denúncias)
--
-- 24  WORKFLOW_DESLIGAMENTO_V2.sql          3 functions,   Sprint 1 P0: workflow
--                                           1 trigger,     de desligamento
--                                           10 colunas em  versionado (antes na
--                                           rh_desligamentos raiz, fora da ordem);
--                                                          executar grava registro
--                                                          analítico; deprecia
--                                                          registrar_desligamento_
--                                                          completo (status inativo)
--
-- 25  DEPLOY_PAGAMENTOS_RH.sql              3 tabelas,     Sprint 1 P0: deploy das
--                                           8 RLS policies tabelas fantasma de
--                                                          pagamentos (dados
--                                                          bancários LGPD, lotes,
--                                                          log de exportação) com
--                                                          RLS RBAC
--
-- 26  WORKFLOW_ADMISSAO_V2.sql              2 functions,   Sprint 2 P1: admissão
--                                           2 colunas de   via processo (candidato
--                                           rastreio,      aprovado -> funcionário);
--                                           1 ALTER        rh_processo.funcionario_id
--                                                          nullable; rastreio
--                                                          candidato -> colaborador
--
-- 27  FERIAS_OPERACIONAL.sql                2 functions,   Sprint 2 P1: férias
--                                           1 CHECK,       operacional — job de
--                                           1 FK NOT VALID vencimento (pendente->
--                                           1 trigger      vencida, CLT 134/137),
--                                                          RPC ferias_programar
--                                                          (abono 1/3 CLT 143);
--                                                          ETL Convenia adiado
--                                                          (payload sem amostra)
--
-- 28  TRIAGEM_DENUNCIAS.sql                 3 functions,   Sprint 2 P1: triagem de
--                                           1 CHECK,       denúncias CIPA — RLS
--                                           2 RLS policies (leitura admin/rh/sst;
--                                           1 trigger      anon só via RPC c/
--                                                          protocolo); consulta
--                                                          pública por protocolo;
--                                                          aberta -> em_analise ->
--                                                          respondida|arquivada
--
-- 29  HARDENING_RLS_MODULOS.sql             ~80 policies   Sprint 3 P2: remove
--                                           1 wrapper fn   TODAS as policies anon;
--                                                          padrão RBAC cipa_acoes
--                                                          em desligamentos, rs_*,
--                                                          benefícios, sst_*,
--                                                          eSocial e CIPA; guard
--                                                          de perfil no
--                                                          motor_decisoes()
--
-- ════════════════════════════════════════════════════════════════════════════
-- TOTAIS ESPERADOS APÓS REBUILD LIMPO:
--   180 tabelas | 33 views | 70+ functions | 63 triggers
--   67 tabelas com RLS | 230 policies
--   (totais a revalidar após UNIFICACAO_SST — rebuild local + contagem)
--   0 erros | 0 tabelas sensíveis expostas
-- ════════════════════════════════════════════════════════════════════════════
