-- Importacao de Fornecedores ATAK para cq_fornecedores
-- Fonte: cq_fornecedores.js (381 fornecedores)
-- Executar no Supabase SQL Editor (projeto Classic-ia CQ)

INSERT INTO public.cq_fornecedores (codigo_atak, nome, nome_normalizado, estado) VALUES
  ('60242', 'A L TRANSPORTES INDUSTRIA E COMERCIO LTDA', 'a l transportes industria e comercio ltda', 'TO'),
  ('60243', 'A M A DA SILVA MOURA', 'a m a da silva moura', 'PA'),
  ('60244', 'A M DA S COSTA', 'a m da s costa', 'MA'),
  ('60161', 'A S SOUZA INDUSTRIA E COMERCIO', 'a s souza industria e comercio', 'TO'),
  ('60032', 'A ZAGO & CIA LTDA ME', 'a zago & cia ltda me', 'RS'),
  ('60180', 'ABATE E DISTRIBUICAO DE CARNES RODEIO LTDA', 'abate e distribuicao de carnes rodeio ltda', 'RS'),
  ('60241', 'ABATEDOURO ALÍPIO ELOI LTDA ME', 'abatedouro alipio eloi ltda me', 'PB'),
  ('60250', 'P L DA SILVA LTDA', 'p l da silva ltda', 'MT'),
  ('60015', 'ABATEDOURO DE BOVINOS LAGOA GRANDE LTDA', 'abatedouro de bovinos lagoa grande ltda', 'PR'),
  ('60194', 'ABATEDOURO DE BOVINOS SAMPAIO LTDA', 'abatedouro de bovinos sampaio ltda', 'PA'),
  ('60267', 'ABATEDOURO FRIGORIFICO SÃO JORGE LTDA', 'abatedouro frigorifico sao jorge ltda', 'SC'),
  ('60146', 'ABATEDOURO SERRANO M A LTDA', 'abatedouro serrano m a ltda', 'MT'),
  ('60030', 'ABAT TIO HUGO LTDA ME', 'abat tio hugo ltda me', 'RS'),
  ('60278', 'ABATEDOURO WS LTDA ME', 'abatedouro ws ltda me', 'MS'),
  ('60360', 'AGRO-X COMERCIO DE GALLSTONE LTDA', 'agro-x comercio de gallstone ltda', 'PR'),
  ('60042', 'AGROBRASIL FRIG LTDA', 'agrobrasil frig ltda', 'RS'),
  ('60236', 'AGROPAMPA FRIGORIFICO LTDA', 'agropampa frigorifico ltda', 'RS'),
  ('60319', 'AGROPECUARIA BARAUNA LTDA', 'agropecuaria barauna ltda', 'PR'),
  ('60197', 'AIRTON KLEIN', 'airton klein', 'RS'),
  ('60016', 'ALACARNE ALIMENTOS EIRELI', 'alacarne alimentos eireli', 'AL'),
  ('60085', 'FRIGORIFICO ALFA - INDUSTRIA E COMERCIO DE CARNES E DERIVADO', 'frigorifico alfa - industria e comercio de carnes e derivado', 'SP'),
  ('60285', 'FRIGORIFICO ALIANÇA', 'frigorifico alianca', 'PA'),
  ('60290', 'ALPHAMETAIS PRODUTOS LTDA', 'alphametais produtos ltda', 'SP'),
  ('60358', 'AMERICAN FRIGO DO BRASIL LTDA', 'american frigo do brasil ltda', 'SC'),
  ('60013', 'FRIG ANGUS LTDA', 'frig angus ltda', 'RS'),
  ('60024', 'FRIGORIFICO ANICUNS LTDA', 'frigorifico anicuns ltda', 'GO'),
  ('60233', 'ANTONIO FERREIRA MENDONÇA', 'antonio ferreira mendonca', 'RS'),
  ('60052', 'FRIGORIFICO ARABUTA LTDA', 'frigorifico arabuta ltda', 'SC'),
  ('60107', 'FRIGORIFICO CARAJAS LTDA', 'frigorifico carajas ltda', 'PR'),
  ('60014', 'FRIGORIFICO ASTRA DO PARANA LTDA', 'frigorifico astra do parana ltda', 'PR'),
  ('60079', 'FRIGORIFICO AUREFRIG LTDA', 'frigorifico aurefrig ltda', 'SP'),
  ('60261', 'AVICOLA MOURAO CM LTDA', 'avicola mourao cm ltda', 'PR'),
  ('60081', 'FRIGORIFICO SANTA MARIA LTDA', 'frigorifico santa maria ltda', 'SP'),
  ('60307', 'BANCO VOLKSWAGEN S.A', 'banco volkswagen s.a', 'SP'),
  ('60365', 'BARBOSA & CIA LTDA', 'barbosa & cia ltda', 'MG'),
  ('60303', 'BARRA ALIMENTOS LTDA', 'barra alimentos ltda', 'MT'),
  ('60324', 'BERALDI COMERCIO DE CARNES LTDA', 'beraldi comercio de carnes ltda', 'PR'),
  ('60352', 'BERRANTE ALIMENTOS LTDA', 'berrante alimentos ltda', 'GO'),
  ('60301', 'MERCADO E AÇOUGUE BETO LTDA EPP', 'mercado e acougue beto ltda epp', 'SC'),
  ('60330', 'B.H.R COMERCIO DE CARNES LTDA', 'b.h.r comercio de carnes ltda', 'PR'),
  ('60022', 'BOA ESPERANÇA ALIMENTOS LTDA', 'boa esperanca alimentos ltda', 'GO'),
  ('60341', 'FRIGORIFICO EJ LTDA', 'frigorifico ej ltda', 'PR'),
  ('60318', 'BOI DOURADO COMERCIO CARNES LTDA', 'boi dourado comercio carnes ltda', 'BA'),
  ('60288', 'PAULO PEDRO COSTA NETO LTDA', 'paulo pedro costa neto ltda', 'MG'),
  ('60342', 'BOI NOBRE ALIMENTOS LTDA', 'boi nobre alimentos ltda', 'GO'),
  ('60262', 'BOI SUL CARNES LTDA', 'boi sul carnes ltda', 'RS'),
  ('60227', 'BOMBEEF FRIGORIFICO E AGROPECUARIA LTDA', 'bombeef frigorifico e agropecuaria ltda', 'SP'),
  ('60083', 'BON-MART FRIGORIFICO LTDA', 'bon-mart frigorifico ltda', 'SP'),
  ('60213', 'FRIGONELORE', 'frigonelore', 'MT'),
  ('60322', 'VALDEIR CESAR DE MORAIS- MATADOURO', 'valdeir cesar de morais- matadouro', 'PR'),
  ('60113', 'FRIGORIFICO COMERCIAL BOSSONI LT', 'frigorifico comercial bossoni lt', 'SP'),
  ('60020', 'MATADOURO E FRIGORIFICO REGIONAL DE BRUMADO LTDA', 'matadouro e frigorifico regional de brumado ltda', 'BA'),
  ('60218', 'BURITI COMERCIO DE CARNES LTDA', 'buriti comercio de carnes ltda', 'MS'),
  ('60245', 'C CARVALHO DE SOUZA', 'c carvalho de souza', 'AC'),
  ('60077', 'ENTREPOSTO DE CARNES E DERIVADOS SAO JOSE LTDA', 'entreposto de carnes e derivados sao jose ltda', 'SP'),
  ('60133', 'CALIBRE DISTRIBUIDORA DE CARNES LTDA', 'calibre distribuidora de carnes ltda', 'PR'),
  ('60067', 'FRIG CAMPEIRO LTDA', 'frig campeiro ltda', 'RS'),
  ('60082', 'FRIGORIFICO CAMPOS SALLES LTDA', 'frigorifico campos salles ltda', 'SP'),
  ('60188', 'M C CANUTO CAVALCANTE', 'm c canuto cavalcante', 'MA'),
  ('60108', 'ROBERTO CARLOS CAPRINI LTDA', 'roberto carlos caprini ltda', 'PR'),
  ('60308', 'FRIGORÍFICO CARNE NOBRE LTDA', 'frigorifico carne nobre ltda', 'GO'),
  ('60184', 'COMERCIO E DISTRIBUICAO DE CARNES POSTINHO LTDA', 'comercio e distribuicao de carnes postinho ltda', 'SC'),
  ('60069', 'CASA NOSTRA FRIG LTDA', 'casa nostra frig ltda', 'RS'),
  ('60017', 'GUSTAVO ANTONIO DE LIMA CAVALCANTE', 'gustavo antonio de lima cavalcante', 'AL'),
  ('60018', 'JOAO OLIVEIRA CAVALCANTE NETO - ME', 'joao oliveira cavalcante neto - me', 'AL'),
  ('60214', 'CAVALCANTE PRODUTOS DO ABATE LTDA', 'cavalcante produtos do abate ltda', 'MA'),
  ('60176', 'CEARA COUROS EIRELI', 'ceara couros eireli', 'CE'),
  ('60050', 'FRIGORIFICO CECHINEL LTDA', 'frigorifico cechinel ltda', 'SC'),
  ('60147', 'CEDRO FRIGOR ABATES E ALIMENTOS LTDA', 'cedro frigor abates e alimentos ltda', 'SC'),
  ('60374', 'CELIO M BATISTA', 'celio m batista', 'PR'),
  ('60119', 'CENTROESTE ABATEDOURO DE CARNES LTDA', 'centroeste abatedouro de carnes ltda', 'RJ'),
  ('60282', 'DICAVEL DISTRIBUIDORA DE CARNES LTDA', 'dicavel distribuidora de carnes ltda', 'PR'),
  ('60092', 'ASSOCIACAO DOS ACOUGUEIROS DE CIANORTE - ASAC', 'associacao dos acougueiros de cianorte - asac', 'PR'),
  ('60337', 'CINCO ESTRELAS ARTIGOS DE COURO LTDA', 'cinco estrelas artigos de couro ltda', 'BA'),
  ('60106', 'MOYA GIMENES & CIA LTDA', 'moya gimenes & cia ltda', 'PR'),
  ('60210', 'COMERCIAL A8 LTDA', 'comercial a8 ltda', 'PE'),
  ('60221', 'COMERCIAL CAVALCANTE LTDA', 'comercial cavalcante ltda', 'MA'),
  ('60207', 'COMERCIO DE CARNES SANTA LAURA LTDA', 'comercio de carnes santa laura ltda', 'PR'),
  ('60356', 'COMERCIO DE CARNES SIVIERO LTDA', 'comercio de carnes siviero ltda', 'RS'),
  ('60329', 'COMERCIO DE CARNES THREE FRIENDS LTDA', 'comercio de carnes three friends ltda', 'PR'),
  ('60323', 'CONSTANTINO E SENTINELLO LTDA', 'constantino e sentinello ltda', 'PR'),
  ('60054', 'FRIGORIFICO BOM SUCESSO LTDA', 'frigorifico bom sucesso ltda', 'SC'),
  ('60117', 'COPEL DISTRIBUICAO S/A', 'copel distribuicao s/a', 'PR'),
  ('60219', 'CORREIA & MOURA LTDA', 'correia & moura ltda', 'AC'),
  ('60298', 'CRC COMERCIO DE SEBOS LTDA', 'crc comercio de sebos ltda', 'PR'),
  ('60118', 'CURTUME NOROESTE LTDA', 'curtume noroeste ltda', 'PR'),
  ('60373', 'SERRANO AGROINDUSTRIAL LTDA', 'serrano agroindustrial ltda', 'PR'),
  ('60346', 'CURTUME TOURO LTDA', 'curtume touro ltda', 'SP'),
  ('60129', 'DELINER E-COMMERCE LTDA', 'deliner e-commerce ltda', 'SP'),
  ('60005', 'COMERCIAL DESTRO LTDA', 'comercial destro ltda', 'PR'),
  ('60168', 'DISCA LUZ DITRIBUIDORA DE CARNES EIRELI', 'disca luz ditribuidora de carnes eireli', 'PR'),
  ('60277', 'DISTRIB CARNES DERIVADOS ALEXANDRE LTDA', 'distrib carnes derivados alexandre ltda', 'MS'),
  ('60387', 'DISTRIBUIDORA DE CARNES L A LTDA', 'distribuidora de carnes l a ltda', 'PR'),
  ('60240', 'DISTRIBUIDORA DE CARNES RANK LTDA', 'distribuidora de carnes rank ltda', 'SP'),
  ('60225', 'DOM DIOGO', 'dom diogo', 'RS'),
  ('60128', 'EFICIENCIA AMBIENTAL COLETA DE RESIDUOS LTDA', 'eficiencia ambiental coleta de residuos ltda', 'PR'),
  ('60276', 'MATADOURA ESPERANÇA', 'matadoura esperanca', 'MS'),
  ('60090', 'MATADOURO FRIGORIFICO ESTEVES', 'matadouro frigorifico esteves', 'RJ'),
  ('60357', 'EXCELLENCE COUROS LTDA', 'excellence couros ltda', 'RS'),
  ('60246', 'F H DE MEDEIROS', 'f h de medeiros', 'RN'),
  ('60239', 'COUROS 3G', 'couros 3g', 'PR'),
  ('60345', 'FELBOI COMERCIO DE RESIDUOS BOVINOS LTDA', 'felboi comercio de residuos bovinos ltda', 'PR'),
  ('60252', 'M DE L DE MORAES LUZARDO EIRELI', 'm de l de moraes luzardo eireli', 'RO'),
  ('60071', 'FRIG FENIX LTDA', 'frig fenix ltda', 'RS'),
  ('60057', 'FRIGORIFICO FERRARINI', 'frigorifico ferrarini', 'SC'),
  ('60139', 'FMR ALIMENTOS LTDA', 'fmr alimentos ltda', 'SE'),
  ('60001', 'FORNECEDOR REVENDA HOMOLOGAÇÃO', 'fornecedor revenda homologacao', 'PR'),
  ('60216', 'FORTE ALIANCA INDUSTRIA E COMERCIO DE ALIMENTOS LTDA', 'forte alianca industria e comercio de alimentos ltda', 'MS'),
  ('60228', 'FRAMAS CASA DE COUROS E RETALHOS LTDA - EPP', 'framas casa de couros e retalhos ltda - epp', 'SP'),
  ('60222', 'FRAN INTERMEDIACAO & TRANSPORTES LTDA', 'fran intermediacao & transportes ltda', 'PA'),
  ('60372', 'FRASSUL COMERCIO DE ALIMENTOS LTDA', 'frassul comercio de alimentos ltda', 'MT'),
  ('60292', 'FRIAGRO', 'friagro', 'MA'),
  ('60383', 'FRIANA FRIGORIFICO ANA CAROLINA LTDA', 'friana frigorifico ana carolina ltda', 'SC'),
  ('60114', 'FRIBAL FRIGORIFICO BALANCIN LTDA', 'fribal frigorifico balancin ltda', 'SP'),
  ('60326', 'FRIBARREIRAS AGRO INDUSTRIAL DE ALIMENTOS LTDA', 'fribarreiras agro industrial de alimentos ltda', 'BA'),
  ('60053', 'FRIBAZ FRIGORIFICO BAZOTTI LTDA', 'fribaz frigorifico bazotti ltda', 'SC'),
  ('60076', 'ASSISCARNES DISTRIBUIDORA DE CARNES LTDA', 'assiscarnes distribuidora de carnes ltda', 'SP'),
  ('60182', 'FRICARNES DISTRIBUIDORA LTDA', 'fricarnes distribuidora ltda', 'AC'),
  ('60056', 'NILTON DO NASCIMENTO LTDA', 'nilton do nascimento ltda', 'SC'),
  ('60191', 'FRIG DLEON LTDA', 'frig dleon ltda', 'RS'),
  ('60196', 'FRIG ESPINILHO LTDA', 'frig espinilho ltda', 'RS'),
  ('60178', 'FRIG ROSO & DALL AGNOL LTDA', 'frig roso & dall agnol ltda', 'RS'),
  ('60087', 'FRIGORIFICO ILHA SOLTEIRA LTDA', 'frigorifico ilha solteira ltda', 'SP'),
  ('60328', 'PRO BOI CARNES LTDA.', 'pro boi carnes ltda. - go', 'GO'),
  ('60312', 'FRIGORIFICO E COMERCIO DE CARNES MARTINS LTDA', 'frigorifico e comercio de carnes martins ltda', 'AM'),
  ('60361', 'FRIGO HIPER CARNE LTDA', 'frigo hiper carne ltda', 'SE'),
  ('60362', 'FRIGO INTER ABATE E COMERCIO DE CARNES LTDA', 'frigo inter abate e comercio de carnes ltda', 'RJ'),
  ('60023', 'FRIGO PRIME INDUSTRIAL E COMERCIO DE CARNES LTDA', 'frigo prime industrial e comercio de carnes ltda', 'GO'),
  ('60355', 'FRIGO VITORIA DISTRIBUIDORA CARNES LTDA', 'frigo vitoria distribuidora carnes ltda', 'MT'),
  ('60170', 'FRIGOABAT FRIGORIFICO ABATEDOURO COSTA TAVARES LTDA', 'frigoabat frigorifico abatedouro costa tavares ltda', 'MG'),
  ('60021', 'FRIGOBARRA LTDA', 'frigobarra ltda', 'ES'),
  ('60009', 'FRIGOBECKER - COMERCIO DE CARNES LTDA', 'frigobecker - comercio de carnes ltda', 'PR'),
  ('60044', 'FRIGOBENDO FRIGORIFICO BENDO LTDA', 'frigobendo frigorifico bendo ltda', 'PR'),
  ('60111', 'FRIGOCENTER IND. E COM. DE CARNES LTDA', 'frigocenter ind. e com. de carnes ltda', 'PR'),
  ('60350', 'FRIGORIFICO REGIONAL DO PIEMONTE DA CHAPADA LTDA', 'frigorifico regional do piemonte da chapada ltda', 'BA'),
  ('60099', 'A M FIRMINO & CIA LTDA', 'a m firmino & cia ltda', 'PR'),
  ('60004', 'FRIGODASKO INDUSTRIA E COMERCIO DE CARNES LTDA', 'frigodasko industria e comercio de carnes ltda', 'PR'),
  ('60310', 'FRIGODIA ALIMENTOS LTDA', 'frigodia alimentos ltda', 'MG'),
  ('60028', 'FRIGORIFICO FRIGOEURO LTDA', 'frigorifico frigoeuro ltda', 'PR'),
  ('60333', 'FRIGOFORT LTDA', 'frigofort ltda', 'PR'),
  ('60091', 'FRIGORIFICO FOX LTDA', 'frigorifico fox ltda', 'SC'),
  ('60283', 'FRIGOIAS INDUSTRIA & COMERCIO DE CARNE LTDA', 'frigoias industria & comercio de carne ltda', 'GO'),
  ('60215', 'FRIGOJAN ALIMENTOS LTDA', 'frigojan alimentos ltda', 'MG'),
  ('60012', 'ABATEDOURO E FRIGORIFICO COLIDER LTDA - ME', 'abatedouro e frigorifico colider ltda - me', 'MT'),
  ('60344', 'JARAGUA ALIMENTOS LTDA', 'jaragua alimentos ltda', 'GO'),
  ('60187', 'FRIGOMATA LTDA - ME', 'frigomata ltda - me', 'MG'),
  ('60212', 'FRIGONE FRIGORIFICO LTDA', 'frigone frigorifico ltda', 'MT'),
  ('60043', 'M.M.M. COMINESI FRIGORIFICO LTDA', 'm.m.m. cominesi frigorifico ltda', 'PR'),
  ('60049', 'MARCELO DOS SANTOS ME', 'marcelo dos santos me', 'SC'),
  ('60381', 'FRIGONOR FRIGORIFICO & COMERCIO LTDA', 'frigonor frigorifico & comercio ltda', 'MG'),
  ('60384', 'FRIGONOR FRIGORIFICO & LOGISTICA LTDA', 'frigonor frigorifico & logistica ltda', 'MG'),
  ('60367', 'FRIGOPAIVA LTDA', 'frigopaiva ltda', 'MG'),
  ('60093', 'FRIGORAES DISTRIBUIDORA DE GENEROS ALIMENTICIOS, INDUSTRIA E', 'frigoraes distribuidora de generos alimenticios, industria e', 'SP'),
  ('60051', 'ADILSON LUCKMANN', 'adilson luckmann', 'SC'),
  ('60171', 'FRIGORIFICO ANA ROSA LTDA', 'frigorifico ana rosa ltda', 'SC'),
  ('60008', 'FRIGORIFICO ARGUS LTDA', 'frigorifico argus ltda', 'PR'),
  ('60232', 'FRIGORIFICO BERRANTE - LTDA', 'frigorifico berrante - ltda', 'GO'),
  ('60031', 'ELENIR INES ALTISSIMO BIEGER', 'elenir ines altissimo bieger', 'RS'),
  ('60172', 'FRIGORIFICO BOI BRAVO INDUSTRIA E COMERCIO LTDA', 'frigorifico boi bravo industria e comercio ltda', 'MG'),
  ('60195', 'FRIGORIFICO BOI CORO LTDA', 'frigorifico boi coro ltda', 'MG'),
  ('60220', 'FRIGORIFICO BONNA CARNE LTDA', 'frigorifico bonna carne ltda', 'RS'),
  ('60209', 'FRIGORIFICO CACOAL LTDA', 'frigorifico cacoal ltda', 'RO'),
  ('60163', 'FRIGORIFICO CAMPO DO GADO AGROINDUSTRIA LTDA', 'frigorifico campo do gado agroindustria ltda', 'BA'),
  ('60314', 'FRIGORIFICO CARNE NOBRE', 'frigorifico carne nobre', 'DF'),
  ('60265', 'FRIGORIFICO CHAPARRAL LTDA', 'frigorifico chaparral ltda', 'MG'),
  ('60363', 'FRIGORIFICO CONFIANCA LTDA', 'frigorifico confianca ltda', 'MG'),
  ('60011', 'FRIGORIFICO CRISTAL S.A.', 'frigorifico cristal s.a.', 'RS'),
  ('60270', 'FRIGORIFICO D'' MATTA COMERCIO E INDUSTRIA LTDA', 'frigorifico d'' matta comercio e industria ltda', 'BA'),
  ('60223', 'FRIGORIFICO DERGI LTDA', 'frigorifico dergi ltda', 'PR'),
  ('60033', 'COM DE CARNES DIETER LTDA', 'com de carnes dieter ltda', 'RS'),
  ('60169', 'MATADOURO SAO GERALDO LTDA', 'matadouro sao geraldo ltda', 'MG'),
  ('60192', 'FRIGORIFICO EING LTDA', 'frigorifico eing ltda', 'SC'),
  ('60124', 'FRIGORIFICO EP AGROPECUARIA LTDA', 'frigorifico ep agropecuaria ltda', 'MT'),
  ('60351', 'FRIGORIFICO ESTRELA DO SUL LTDA', 'frigorifico estrela do sul ltda', 'ES'),
  ('60134', 'FRIGORIFICO FRANCA BOI LTDA', 'frigorifico franca boi ltda', 'SP'),
  ('60103', 'FRIGORIFICO FRIGOANGUS LTDA', 'frigorifico frigoangus ltda', 'PR'),
  ('60275', 'FRIGORIFICO FRIGOMENDES LTDA', 'frigorifico frigomendes ltda', 'PR'),
  ('60335', 'SUELY DOMINGAS VAHL DOS SANTOS', 'suely domingas vahl dos santos', 'RS'),
  ('60179', 'FRIGORIFICO IPER LTDA', 'frigorifico iper ltda', 'MG'),
  ('60152', 'FRIGORIFICO IRMAOS SCAPINI LTDA', 'frigorifico irmaos scapini ltda', 'PR'),
  ('60315', 'FRIGORIFICO J.A & FILHO LTDA', 'frigorifico j.a & filho ltda', 'SP'),
  ('60098', 'FRIGORIFICO JR LTDA', 'frigorifico jr ltda', 'PR'),
  ('60211', 'FRIGORIFICO KLEIN LTDA', 'frigorifico klein ltda', 'SC'),
  ('60271', 'FRIGORIFICO KLUG LTDA', 'frigorifico klug ltda', 'RS'),
  ('60368', 'FRIGORIFICO LUCIANA LTDA', 'frigorifico luciana ltda', 'MG'),
  ('60097', 'FRIGORIFICO LUZENSE', 'frigorifico luzense', 'MG'),
  ('60007', 'FRIGORIFICO MATADOURO GUAREI LTDA', 'frigorifico matadouro guarei ltda', 'SP'),
  ('60347', 'FRIGORIFICO MK LTDA', 'frigorifico mk ltda', 'RS'),
  ('60175', 'FRIGORIFICO MODELO LTDA', 'frigorifico modelo ltda', 'BA'),
  ('60247', 'FRIGORIFICO MONTANHA LTDA', 'frigorifico montanha ltda', 'ES'),
  ('60136', 'FRIGORIFICO MUQUEM DO SAO FRANCISCO LTDA', 'frigorifico muquem do sao francisco ltda', 'BA'),
  ('60116', 'FRIGORIFICO NOSSA SENHORA APARECIDA LTDA.', 'frigorifico nossa senhora aparecida ltda.', 'PR'),
  ('60149', 'FRIGORIFICO NOVA ALIANCA LTDA', 'frigorifico nova alianca ltda', 'RJ'),
  ('60166', 'FRIGOPOTI - FRIGORIFICO POTI LTDA', 'frigopoti - frigorifico poti ltda', 'SP'),
  ('60269', 'FRIGORIFICO PREMIUM INDUSTRIA E COMERCIO DE CARNES LTDA', 'frigorifico premium industria e comercio de carnes ltda', 'GO'),
  ('60268', 'FRIGORIFICO RE', 'frigorifico re', 'SC'),
  ('60138', 'FRIGORIFICO REGIONAL DE ALAGOINHAS LTDA', 'frigorifico regional de alagoinhas ltda', 'BA'),
  ('60266', 'FRIGORIFICO REGIONAL SUDOESTE LTDA', 'frigorifico regional sudoeste ltda', 'BA'),
  ('60145', 'FRIGORIFICO RIO BONITO S/A', 'frigorifico rio bonito s/a', 'MT'),
  ('60185', 'FRIG RZ PRODOTTI LA DELIZIA LTDA', 'frig rz prodotti la delizia ltda', 'RS'),
  ('60369', 'FRIGORIFICO SAO JOAO DEL REI LTDA', 'frigorifico sao joao del rei ltda', 'MG'),
  ('60348', 'FRIGO SERRANO AGROINDUSTRIAL LTDA', 'frigo serrano agroindustrial ltda', 'SE'),
  ('60155', 'FRIGORIFICO TMJ LTDA', 'frigorifico tmj ltda', 'PR'),
  ('60202', 'FRIGORIFICO VALENCIO LTDA', 'frigorifico valencio ltda', 'PA'),
  ('60143', 'FRIGORIFICO VIDAURRE LTDA', 'frigorifico vidaurre ltda', 'RJ'),
  ('60237', 'FRIGORIFICO ZART LTDA', 'frigorifico zart ltda', 'RS'),
  ('60224', 'FRIGORINI INDUSTRIA E COMERCIO DE CARNES LTDA', 'frigorini industria e comercio de carnes ltda', 'PR'),
  ('60189', 'FRIG BETANIN LTDA', 'frig betanin ltda', 'RS'),
  ('60359', 'FRIGOSAJ FRIGORIFICO LTDA', 'frigosaj frigorifico ltda', 'BA'),
  ('60249', 'SERCOL - SERVICO E COMERCIO DO VALE LTDA', 'sercol - servico e comercio do vale ltda', 'MG'),
  ('60385', 'SANDER E CIA LTDA', 'sander e cia ltda', 'SC'),
  ('60006', 'FRIGOSCHAEDLER LTDA', 'frigoschaedler ltda', 'PR'),
  ('60349', 'FRIGOSSERRA - FRIGORIFICO REGIONAL DE SERRINHA LTDA', 'frigosserra - frigorifico regional de serrinha ltda', 'BA'),
  ('60026', 'FRIGOSTEAK ALIMENTOS LTDA', 'frigosteak alimentos ltda', 'GO'),
  ('60003', 'FRIGOTERRA ALIMENTOS LTDA', 'frigoterra alimentos ltda', 'SP'),
  ('60062', 'FRIGOTOTI ABATEDOURO LTDA', 'frigototi abatedouro ltda', 'SC'),
  ('60305', 'FRIGOVALE DO GUAPORE COM. E IND. DE CARNES LTDA', 'frigovale do guapore com. e ind. de carnes ltda', 'AL'),
  ('60289', 'FRIGOVILLE INDUSTRIA E COMERCIO DE CARNES LTDA', 'frigoville industria e comercio de carnes ltda', 'PR'),
  ('60291', 'FRIGOVIP ALIMENTOS LTDA', 'frigovip alimentos ltda', 'GO'),
  ('60336', 'FRIGORIFICO ANCHIETA EIRELI', 'frigorifico anchieta eireli', 'ES'),
  ('60162', 'FRIHELP FRIGORIFICO VALE DAS AGUAS LTDA', 'frihelp frigorifico vale das aguas ltda', 'SP'),
  ('60137', 'FRIJACUIPE MATADOURO E FRIGORIFICO LTDA', 'frijacuipe matadouro e frigorifico ltda', 'BA'),
  ('60311', 'FRIGORIFICO FRILEM LTDA', 'frigorifico frilem ltda', 'BA'),
  ('60370', 'FRIMATOS FRIGORIFICO IRMAOS MATOS LTDA', 'frimatos frigorifico irmaos matos ltda', 'BA'),
  ('60063', 'FRINORA FRIGORIFICO LTDA', 'frinora frigorifico ltda', 'SC'),
  ('60142', 'FRIQUALI ALIMENTOS LTDA', 'friquali alimentos ltda', 'SC'),
  ('60295', 'FRIGORIFICO RONDONOPOLIS LTDA', 'frigorifico rondonopolis ltda', 'MT'),
  ('60130', 'FRISAJO AGRO PECUARIA INDUSTRIAL LTDA', 'frisajo agro pecuaria industrial ltda', 'SC'),
  ('60353', 'FRISPAR FRIGORIFICO SUDOESTE DO PARANA LTDA', 'frispar frigorifico sudoeste do parana ltda', 'PR'),
  ('60331', 'FRIZONTE - INDUSTRIA DE ALIMENTOS LTDA', 'frizonte - industria de alimentos ltda', 'PR'),
  ('60327', 'G S BERTONCELLI - FRIGORIFICO', 'g s bertoncelli - frigorifico', 'PR'),
  ('60065', 'FRIG GASSEN LTDA', 'frig gassen ltda', 'RS'),
  ('60084', 'GOLD CARNES COMERCIO ATACADISTA DE CARNES E DERIVADOS LTDA', 'gold carnes comercio atacadista de carnes e derivados ltda', 'SP'),
  ('60238', 'GONEXT MEAT FOOD LTDA', 'gonext meat food ltda', 'PR'),
  ('60132', 'GR TRANSPORTE E COMERCIO LTDA', 'gr transporte e comercio ltda', 'RJ'),
  ('60258', 'J  P S COMERCIO DE CARNES LTDA', 'j  p s comercio de carnes ltda', 'RJ'),
  ('60386', 'GUSTAVO ANTONIO DE LIMA CAVALCANTE LTDA', 'gustavo antonio de lima cavalcante ltda', 'PE'),
  ('60154', 'HS MEAT FOOD LTDA', 'hs meat food ltda', 'PR'),
  ('60190', 'I X DE SOUZA', 'i x de souza', 'RO'),
  ('60248', 'I. O. PEIXOTO IMPORTACAO EXPORTACAO', 'i. o. peixoto importacao exportacao', 'AC'),
  ('60029', 'INCOPROVER IND E COM DE PROTEINA LTDA', 'incoprover ind e com de proteina ltda', 'RS'),
  ('60156', 'INTERCOUROS INTERMED. IMPORT. ,EXPOR E COMERCIO DE COURO', 'intercouros intermed. import. ,expor e comercio de couro', 'BA'),
  ('60284', 'INTERCOUROS INTERMEDIACAO, IMPORTACAO, EXPORTACAO E COMERCIO', 'intercouros intermediacao, importacao, exportacao e comercio', 'BA'),
  ('60036', 'IRMAOS MERTEN LTDA', 'irmaos merten ltda', 'RS'),
  ('60070', 'FRIG IRMAOS ROSA LTDA', 'frig irmaos rosa ltda', 'RS'),
  ('60274', 'ITAJARA COMERCIO DE CARNES LTDA', 'itajara comercio de carnes ltda', 'SP'),
  ('60302', 'ITHALO PRADO CUSTODIO', 'ithalo prado custodio', 'MT'),
  ('60235', 'FRIGOVEMA', 'frigovema', 'MS'),
  ('60193', 'J A DA SILVA BEZERROS EIRELI - ME', 'j a da silva bezerros eireli - me', 'PE'),
  ('60181', 'J ALTEVI DO PRADO EPP', 'j altevi do prado epp', 'PA'),
  ('60317', 'J G W COMERCIO DE CARNES E DERIVADOS LTDA', 'j g w comercio de carnes e derivados ltda', 'MS'),
  ('60140', 'J GUSMAO & CIA LTDA', 'j gusmao & cia ltda', 'AL'),
  ('60260', 'JPS COMERCIO DE CARNES LTDA', 'jps comercio de carnes ltda', 'RJ'),
  ('60089', 'FRIGORIFICO JABURU LTDA', 'frigorifico jaburu ltda', 'RJ'),
  ('60334', 'JACOB & BATTISTI LTDA', 'jacob & battisti ltda', 'PR'),
  ('60300', 'FRIGORIFICO JATOBA', 'frigorifico jatoba', 'TO'),
  ('60148', 'JEAN CARLOS DOS SANTOS - CARNES - ME', 'jean carlos dos santos - carnes - me', 'PR'),
  ('60064', 'LUCAS CARDOSO DA SILVA', 'lucas cardoso da silva', 'SC'),
  ('60201', 'JLS FRIGORIFICO LTDA', 'jls frigorifico ltda', 'SC'),
  ('60257', 'MATADOURO JORGE DETTMANN', 'matadouro jorge dettmann', 'RS'),
  ('60102', 'JOSE MARCIO FERREIRA  LTDA', 'jose marcio ferreira  ltda', 'PR'),
  ('60027', 'FRIGORIFICO BOI GORDO LTDA', 'frigorifico boi gordo ltda', 'PR'),
  ('60112', 'J.R. LEME  - ME', 'j.r. leme  - me', 'SP'),
  ('60293', 'K. A. REPRESENTAÇÃO E DISTRIBUIDOR DE CARNES FRESCAS LTDA', 'k. a. representacao e distribuidor de carnes frescas ltda', 'GO'),
  ('60273', 'KM DISTRIBUIDORA SE CARNES LTDA', 'km distribuidora se carnes ltda', 'RJ'),
  ('60150', 'KRM REPRESENTANTE, COMERCIO E TRANSPORTADORA', 'krm representante, comercio e transportadora', 'RJ'),
  ('60254', 'L K J - FRIGORIFICO LTDA', 'l k j - frigorifico ltda', 'TO'),
  ('60253', 'L. LOPES COMERCIO DE COUROS', 'l. lopes comercio de couros', 'SP'),
  ('60088', 'J S FERREIRA  FRIGORIFICO LTDA', 'j s ferreira  frigorifico ltda', 'RJ'),
  ('60316', 'LFS REPRESENTANTE TRANSPORTE E COMERCIO', 'lfs representante transporte e comercio', 'RJ'),
  ('60127', 'LOPES LUBRIFICANTES LTDA', 'lopes lubrificantes ltda', 'PR'),
  ('60073', 'DISTRIBUIDORA DE CARNES LUCIANETTI LTDA', 'distribuidora de carnes lucianetti ltda', 'SP'),
  ('60229', 'LUCIANO ALVES TETE RECICLAGEM E TRANSPORTES LTDA', 'luciano alves tete reciclagem e transportes ltda', 'PR'),
  ('60165', 'FRIGORIFICO BISMARK LTDA', 'frigorifico bismark ltda', 'SC'),
  ('60186', 'N Z LUZARDO COMERCIO ATACADISTA DE CARNES E DERIVADOS LTDA', 'n z luzardo comercio atacadista de carnes e derivados ltda', 'RO'),
  ('60375', 'M A FOOD LTDA', 'm a food ltda', 'PR'),
  ('60075', 'M A LEME AGROPECUARIA LTDA', 'm a leme agropecuaria ltda', 'SP'),
  ('60041', 'FRIG M.A. LTDA', 'frig m.a. ltda', 'RS'),
  ('60256', 'FRIGORIFICO MADU', 'frigorifico madu', 'RS'),
  ('60055', 'FRIGORIFICO E DISTRIBUIDORA DE CARNES MAGIA LTDA', 'frigorifico e distribuidora de carnes magia ltda', 'SC'),
  ('60109', 'R B MAIOLI', 'r b maioli', 'PR'),
  ('60086', 'FRIGORIFICO MARANA LTDA', 'frigorifico marana ltda', 'SP'),
  ('60120', 'MARCIO LOPES CAVALCANTE', 'marcio lopes cavalcante', 'AL'),
  ('60174', 'MARCOS DA C CAVALCANTE', 'marcos da c cavalcante', 'MA'),
  ('60200', 'MARINES B FERREIRA', 'marines b ferreira', 'RS'),
  ('60177', 'M RIBEIRO SUBPRODUTOS BOVINOS LTDA', 'm ribeiro subprodutos bovinos ltda', 'PR'),
  ('60309', 'FRIGOMAX LTDA', 'frigomax ltda', 'SC'),
  ('60144', 'MBS FRIGORIFICO LTDA', 'mbs frigorifico ltda', 'MT'),
  ('60204', 'MCL IND E COM DE CARNES E DER EIRELI', 'mcl ind e com de carnes e der eireli', 'AC'),
  ('60251', 'METEORO ALIMENTOS LTDA', 'meteoro alimentos ltda', 'RS'),
  ('60121', 'MG COUROS', 'mg couros', 'PE'),
  ('60151', 'MINNER COML LTDA', 'minner coml ltda', 'RS'),
  ('60080', 'FRIGORIFICO MIRELLA LTDA', 'frigorifico mirella ltda', 'SP'),
  ('60078', 'MONTALFRIG FRIGORIFICO INDUSTRIA E COMERCIO DE CARNES LTDA', 'montalfrig frigorifico industria e comercio de carnes ltda', 'SP'),
  ('60123', 'MONTEBELO INDUSTRIA E COMÉRCIO DE CARNES S/A', 'montebelo industria e comercio de carnes s/a', 'SC'),
  ('60272', 'MATADOURO MORRO AGUDO', 'matadouro morro agudo', 'SP'),
  ('60105', 'FRIGORIFICO CRISTAL LTDA', 'frigorifico cristal ltda', 'PR'),
  ('60126', 'MULTILOG BRASIL S.A.', 'multilog brasil s.a.', 'PR'),
  ('60388', 'N PEDRO GRANDO & CIA LTDA', 'n pedro grando & cia ltda', 'PR'),
  ('60339', 'NILSON FERNANDO WOLPI DE OLIVEIRA LTDA', 'nilson fernando wolpi de oliveira ltda', 'PR'),
  ('60037', 'CASA DAS CARNES NOVA PRATA LTDA', 'casa das carnes nova prata ltda', 'RS'),
  ('60122', 'A J DE OLIVEIRA COMERCIO DE SAL MARINHO LTDA', 'a j de oliveira comercio de sal marinho ltda', 'RN'),
  ('60294', 'NUTRIAL AGROINDUSTRIAS REUNIDAS S/A', 'nutrial agroindustrias reunidas s/a', 'SE'),
  ('60167', 'ORFIMAR COMERCIO DE CARNES LTDA', 'orfimar comercio de carnes ltda', 'PR'),
  ('60010', 'ORION & MAGISTRAL LTDA.', 'orion & magistral ltda.', 'PR'),
  ('60025', 'FRIGORIFICO OURO VERDE LTDA', 'frigorifico ouro verde ltda', 'GO'),
  ('60304', 'FRIG PAI NOSSO & MONTE SIAO LTDA', 'frig pai nosso & monte siao ltda', 'RS'),
  ('60059', 'PAMPLONA ALIMENTOS S/A', 'pamplona alimentos s/a', 'SC'),
  ('60320', 'FRIGORIFICO PARACATU LTDA', 'frigorifico paracatu ltda', 'MG'),
  ('60046', 'FRIGORIFICO PAULO VIOLA DE ITAPIRA LTDA', 'frigorifico paulo viola de itapira ltda', 'SP'),
  ('60208', 'VALTERLICE FERREIRA FORNEL & CIA LTDA', 'valterlice ferreira fornel & cia ltda', 'SP'),
  ('60131', 'PEDRO CECONI', 'pedro ceconi', 'SC'),
  ('60198', 'PLANETA COUROS LTDA', 'planeta couros ltda', 'PE'),
  ('60039', 'FRIGORIFICO POCA EIRELI', 'frigorifico poca eireli', 'RS'),
  ('60100', 'DISTRIBUIDORA DE CARNES PORBOI LTDA', 'distribuidora de carnes porboi ltda', 'PR'),
  ('60205', 'PRLC SERVICOS LTDA', 'prlc servicos ltda', 'MA'),
  ('60377', 'PRO BOI CARNES LTDA.', 'pro boi carnes ltda. - sp', 'SP'),
  ('60338', 'PROL PRODUTOS DO ABATE LTDA', 'prol produtos do abate ltda', 'MA'),
  ('60325', 'R B SÓ CARNE DISTRIBUIDORA LTDA', 'r b so carne distribuidora ltda', 'GO'),
  ('60159', 'R.A.G COSTA CARNES LTDA', 'r.a.g costa carnes ltda', 'PR'),
  ('60040', 'RAHMEIER MERCADO E DISTRIB LTDA', 'rahmeier mercado e distrib ltda', 'RS'),
  ('60101', 'R S B COMERCIO DE MIUDOS LTDA', 'r s b comercio de miudos ltda', 'PR'),
  ('60343', 'RAMAX CACHOEIRA ALTA LTDA', 'ramax cachoeira alta ltda', 'GO'),
  ('60048', 'FRIG RAMOS LTDA', 'frig ramos ltda', 'RS'),
  ('60371', 'REAL SUBPRODUTOS LTDA', 'real subprodutos ltda', 'SE'),
  ('60034', 'RECRISUL COM DE CARNES LTDA', 'recrisul com de carnes ltda', 'RS'),
  ('60259', 'RIBEIRO INDUSTRIA E COMERCIO DE EMBOLOS DE VEDACAO LTDA', 'ribeiro industria e comercio de embolos de vedacao ltda', 'PR'),
  ('60364', 'RICARDO DE OLIVEIRA', 'ricardo de oliveira', 'PR'),
  ('60096', 'FRIGORIFICO VIEIRA E VENDRAME LTDA', 'frigorifico vieira e vendrame ltda', 'PR'),
  ('60332', 'MATADOURO O T J LTDA EPP', 'matadouro o t j ltda epp', 'GO'),
  ('60299', 'RICARDO MARQUES DE AZEVEDO LTDA', 'ricardo marques de azevedo ltda', 'PR'),
  ('60199', 'C M FARIAS ROSSATO & CIA. LTDA', 'c m farias rossato & cia. ltda', 'PR'),
  ('60135', 'ROSSI FRIGORIFICO LTDA', 'rossi frigorifico ltda', 'SC'),
  ('60287', 'FRIGORIFICO RV LTDA', 'frigorifico rv ltda', 'SP'),
  ('60306', 'SAGGIORATO COMERCIO DE COURO LTDA', 'saggiorato comercio de couro ltda', 'SC'),
  ('60379', 'SAL POTIGUAR COMERCIO E INDUSTRIA LTDA', 'sal potiguar comercio e industria ltda', 'RN'),
  ('60286', 'SALINA DIAMANTE BRANCO LTDA', 'salina diamante branco ltda', 'RN'),
  ('60058', 'FRIGORIFICO SALTO VELOSO', 'frigorifico salto veloso', 'SC'),
  ('60366', 'SANTA LUCIA INDUSTRIA & COMERCIO DE CARNES LTDA', 'santa lucia industria & comercio de carnes ltda', 'MG'),
  ('60035', 'ANDERSON B PEREIRA', 'anderson b pereira', 'RS'),
  ('60104', 'SANTA RITA COMERCIO DE CARNES LTDA ME', 'santa rita comercio de carnes ltda me', 'PR'),
  ('60095', 'FRIGORIFICO SAO FRANCISCO LTDA', 'frigorifico sao francisco ltda', 'PR'),
  ('60045', 'FRIGORIFICO SCAPINI LTDA', 'frigorifico scapini ltda', 'PR'),
  ('60060', 'SCHMITZ AGROPECUARIA INDUSTRIAL LTDA', 'schmitz agropecuaria industrial ltda', 'SC'),
  ('60279', 'FRIGORIFICO SENTINELLA LTDA', 'frigorifico sentinella ltda', 'SP'),
  ('60378', 'SERGIO COLOMBO NETO', 'sergio colombo neto', 'SP'),
  ('60354', 'SF INDUSTRIA E COMERCIO DE CARNES LTDA', 'sf industria e comercio de carnes ltda', 'MT'),
  ('60110', 'SOMA COMERCIO DE PRODUTOS ALIMENTICIOS LTDA', 'soma comercio de produtos alimenticios ltda', 'PR'),
  ('60255', 'SR- BOVINOS LTDA', 'sr- bovinos ltda', 'MG'),
  ('60226', 'SUAVE ALIMENTOS LTDA', 'suave alimentos ltda', 'MG'),
  ('60234', 'SUBPRODUTOS INSUMOS AGROPECUARIO LTDA', 'subprodutos insumos agropecuario ltda', 'PR'),
  ('60164', 'SUINOS MACHADO DISTRIBUIDORA DE CARNES LTDA', 'suinos machado distribuidora de carnes ltda', 'BA'),
  ('60066', 'FRIG SULNORTE IND E COM DE CARNES LTDA', 'frig sulnorte ind e com de carnes ltda', 'RS'),
  ('60217', 'SUPER LIDER DISTRIBUIDORA DE CARNES LTDA', 'super lider distribuidora de carnes ltda', 'MS'),
  ('60153', 'T R COUROS LTDA', 't r couros ltda', 'ES'),
  ('60297', 'TALISMA ALIMENTOS LTDA', 'talisma alimentos ltda', 'GO'),
  ('60019', 'FRIGORÍFICO TAURO LTDA', 'frigorifico tauro ltda', 'BA'),
  ('60158', 'TERESINA ABATE DE BOVINOS', 'teresina abate de bovinos', 'PI'),
  ('60296', 'TOP BOI- COMERCIO DE CARNES E DERIVADOS LTDA', 'top boi- comercio de carnes e derivados ltda', 'RJ'),
  ('60173', 'TRADE FORTY-FOUR COMERCIO DE SUBPRODUTOS BOVINOS LTDA', 'trade forty-four comercio de subprodutos bovinos ltda', 'PR'),
  ('60382', 'UNIFRIGO FRIGORIFICO LTDA', 'unifrigo frigorifico ltda', 'MG'),
  ('60380', 'UNISAL-UNIAO SALINEIRA LTDA', 'unisal-uniao salineira ltda', 'RN'),
  ('60206', 'V MARIO DE OLIVEIRA', 'v mario de oliveira', 'RS'),
  ('60141', 'VADECAR MATADOURO LTDA', 'vadecar matadouro ltda', 'RJ'),
  ('60125', 'VALE DO BOI ALIMENTOS LTDA', 'vale do boi alimentos ltda', 'GO'),
  ('60072', 'FRIGORIFICO VALE DO PRATA LTDA', 'frigorifico vale do prata ltda', 'SP'),
  ('60061', 'FRIGORIFICO VARPI LTDA', 'frigorifico varpi ltda', 'SC'),
  ('60068', 'MATADOURO VENZKE LTDA', 'matadouro venzke ltda', 'RS'),
  ('60094', 'VEREDA ALIMENTOS LTDA', 'vereda alimentos ltda', 'GO'),
  ('60183', 'VIA CARNES INDUSTRIA E COMERCIO LTDA', 'via carnes industria e comercio ltda', 'GO'),
  ('60281', 'FRIGORIFICO VIANNA', 'frigorifico vianna', 'RS'),
  ('60280', 'VITAPELLI LTDA', 'vitapelli ltda', 'SP'),
  ('60264', 'VOONKE DO BRASIL PRODUTOS QUIMICOS INDUSTRIAL LTDA', 'voonke do brasil produtos quimicos industrial ltda', 'SC'),
  ('60115', 'FRIGORIFICO V R LTDA', 'frigorifico v r ltda', 'SP'),
  ('60376', 'WASHINGTON EMILIO PINTON MORRO AGUDO LTDA', 'washington emilio pinton morro agudo ltda', 'SP'),
  ('60231', 'WENDEL', 'wendel', 'BA'),
  ('60203', 'FERNANDO WOLPI DE OLIVEIRA SUPERMERCADO LTDA', 'fernando wolpi de oliveira supermercado ltda', 'PR'),
  ('60263', 'XANXERE RAFIA INDUSTRIA DE TECIDOS TECNICOS LTDA', 'xanxere rafia industria de tecidos tecnicos ltda', 'SC'),
  ('60321', 'YIPE AGROPECUARIA LTDA', 'yipe agropecuaria ltda', 'PR'),
  ('60038', 'ZANIN COM DE PROD ALIMENTOS LTDA', 'zanin com de prod alimentos ltda', 'RS'),
  ('60047', 'ABAT ZEBUA LTDA', 'abat zebua ltda', 'RS')
ON CONFLICT (codigo_atak) DO UPDATE SET
  nome = EXCLUDED.nome,
  nome_normalizado = EXCLUDED.nome_normalizado,
  estado = EXCLUDED.estado,
  ativo = true,
  atualizado_em = now();

-- Verificar
SELECT count(*) as total_fornecedores FROM public.cq_fornecedores;
